name: Build and Deploy the Container to Google Compute Engine
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: ${{ github.event.repository.name }}

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code from the repository
        id: checkout
        uses: actions/checkout@v2.4.0

      - name: Set up the Google Cloud SDK
        id: setup-gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Register Google Cloud SDK as a Docker credential helper
        id: register-gcloud-docker
        run: gcloud auth configure-docker

      - name: Build the Docker image
        id: build-image
        run: docker build . -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.ref_name }} -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest

      - name: Publish the Docker image
        id: publish-image
        run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }} --all-tags

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Google Compute Engine through a webhook
        id: deploy-container
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: http://${{ secrets.WEBHOOK_IP }}:9000/hooks/deploy-${{ env.SERVICE }}
          body: '{ "secret": "${{ secrets.WEBHOOK_SECRET }}" }'
